### ISSUE TITLE
Create a fasta reader

### ISSUE THREAD

**Issue by BenjamLouis** [EPFL-SV-cpp-projects/Team_19#3]
Maybe use the fasta reader implemented in the first assignment. Adapt the code so that it does read the whole file at once, but one sequence at a time.

**Comment by yibnl** [comment]
The issue is considered done. However, if you do want to write a test program, you'd better use GTest instead of writing messages to the standard output. In the particular case of _test_fasta.cpp_, you're calling _display_ and _displayNucle_ instead of doing assertions.
