### ISSUE TITLE
Clean the code and comment all files

### ISSUE THREAD

**Issue by Nchennoufi** [EPFL-SV-cpp-projects/Team_19#31]

**Comment by yibnl** [comment]
You need to get rid of the comments in the following lines:
- https://github.com/EPFL-SV-cpp-projects/Team_19/blob/master/src/Matrice.cpp#L167
- https://github.com/EPFL-SV-cpp-projects/Team_19/blob/master/src/MatrixReader.cpp#L81
- https://github.com/EPFL-SV-cpp-projects/Team_19/blob/master/src/MatrixWriter.cpp#L23
- https://github.com/EPFL-SV-cpp-projects/Team_19/blob/master/src/MatrixWriter.cpp#L28

**Comment by yibnl** [comment]
Also, you guys need to document the exceptions that your methods may throw. You basically need to add `@throw exception description` in your `.h` files.
