### ISSUE TITLE
Create a bed reader

### ISSUE THREAD

**Issue by BenjamLouis** [EPFL-SV-cpp-projects/Team_19#4]
Implement a bed reader according to the standard format. Handle the optional values. You can define a BedEntry class that defines attributes relevant to the file format.

**Comment by yibnl** [comment]
`\t` is the ASCII character that describes a tab. Initialize your variable _delimiter_ with this character.

**Comment by yibnl** [comment]
You may consider changing a bit your API. Currently, you read the whole file each time you want to find a specific line. It would be better to read the file once, in the constructor for instance. Your _read_ method could expect a sequence name and then return the corresponding sequence.

The constraint of reading a whole file applies only to the _fasta_ file according to the project specification. As a consequence, you're free to read the _BED_ file all at once.
